### ISSUE TITLE
Lu Chipman Decomposition can produce invalid mueller matrix

### ISSUE THREAD

**Issue by dvincentwest** [usnistgov/SCATMECH#4] opened 2019-10-10 21:14 UTC
It looks like it could just be related to numerical precision, but I wanted to do a Lu Chipman Decomposition of a Mueller Matrix, and the depolarizing matrix produced was deemed to be invalid.  It seems like there might be very small deltas in some of the zeros, but also it seems like the code should probably handle these kinds of scenarios somehow.

Below is the C++ program demonstrating the issue, along with the output:

```cpp
#include "mueller.h"
#include <stdio.h>
#include <string>

using namespace std;
using namespace SCATMECH;

void print_mm(string title, MuellerMatrix& mm) {
  cout << endl << title << endl;
  for(int i=0; i < 4; i++){
    printf("% 18.14f % 18.14f % 18.14f % 18.14f \n",
           mm[i][0], mm[i][1], mm[i][2], mm[i][3]);
  }
  if (mm.valid()) {cout << "Mueller Matrix is Valid" << endl;}
  else {cout << "Mueller Matrix is NOT Valid" << endl;}
}

int main() {
  MuellerMatrix mm = MuellerZero();
  mm[0][0] = mm[1][1] = 23.05576897;
  mm[0][1] = mm[1][0] = -2.25341964;
  mm[2][2] = mm[3][3] = 22.897892;
  mm[2][3] = 0.39066115;
  mm[3][2] = -0.39066115;

  MuellerMatrix mmP = MuellerZero();
  MuellerMatrix mmR = MuellerZero();
  MuellerMatrix mmD = MuellerZero();

  mm.Lu_Chipman_Decomposition(mmP, mmR, mmD);
  print_mm("Main MM", mm);
  print_mm("Depolarizer", mmP);
  print_mm("Retarder", mmR);
  print_mm("Diattenuator", mmD);

  MuellerMatrix test = MuellerUnit(1.0);
  test[2][2] = test[3][3] = 0.99807550356182;
  print_mm("Test Depolarizer", test);
}
```

to compile I just added this to your Makefile:

```Makefile
muellertest/muellertest : muellertest/muellertest.cpp scatmech.a
	$(COMPILE) -o muellertest/muellertest.o -c muellertest/muellertest.cpp
	$(LINK) -o muellertest/muellertest$(EXE) muellertest/muellertest.o $(LIBRARIES)
```

and it produces this output, note that the Depolarizer is invalid whereas my manually created matrix is valid:

```txt
Main MM
 23.05576897000000  -2.25341964000000   0.00000000000000   0.00000000000000 
 -2.25341964000000  23.05576897000000   0.00000000000000   0.00000000000000 
  0.00000000000000   0.00000000000000  22.89789200000000   0.39066115000000 
  0.00000000000000   0.00000000000000  -0.39066115000000  22.89789200000000 
Mueller Matrix is Valid

Depolarizer
  1.00000000000000   0.00000000000000   0.00000000000000   0.00000000000000 
 -0.00000000000000   1.00000000000000   0.00000000000000   0.00000000000000 
  0.00000000000000   0.00000000000000   0.99807550356182  -0.00000000000000 
  0.00000000000000   0.00000000000000  -0.00000000000000   0.99807550356182 
Mueller Matrix is NOT Valid

Retarder
  1.00000000000000   0.00000000000000   0.00000000000000   0.00000000000000 
  0.00000000000000   1.00000000000000   0.00000000000000   0.00000000000000 
  0.00000000000000   0.00000000000000   0.99985449274432   0.01705852687086 
  0.00000000000000   0.00000000000000  -0.01705852687086   0.99985449274432 
Mueller Matrix is Valid

Diattenuator
 23.05576897000000  -2.25341964000000   0.00000000000000   0.00000000000000 
 -2.25341964000000  23.05576897000000   0.00000000000000   0.00000000000000 
  0.00000000000000   0.00000000000000  22.94538260138795   0.00000000000000 
  0.00000000000000   0.00000000000000   0.00000000000000  22.94538260138795 
Mueller Matrix is Valid

Test Depolarizer
  1.00000000000000   0.00000000000000   0.00000000000000   0.00000000000000 
  0.00000000000000   1.00000000000000   0.00000000000000   0.00000000000000 
  0.00000000000000   0.00000000000000   0.99807550356182   0.00000000000000 
  0.00000000000000   0.00000000000000   0.00000000000000   0.99807550356182 
Mueller Matrix is Valid

```

**Comment by dvincentwest** [comment] 2019-10-11 17:52
Further update,

Here are the values of the decomposition in scientific notation.  Just some very small values close to zero, but perhaps the negative sign in some places makes the polarizer matrix invalid:

```
Polarizer:
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [-4.476307e-18  1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  9.980755e-01 -2.344638e-19]
 [ 0.000000e+00  0.000000e+00 -2.344638e-19  9.980755e-01]]
Retarder:
[[ 1.000000e+00  6.454294e-18  0.000000e+00  0.000000e+00]
 [ 2.235679e-34  1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  9.998545e-01  1.705853e-02]
 [ 0.000000e+00  0.000000e+00 -1.705853e-02  9.998545e-01]]
Diattenuator:
[[23.055769 -2.25342   0.        0.      ]
 [-2.25342  23.055769  0.        0.      ]
 [ 0.        0.       22.945383  0.      ]
 [ 0.        0.        0.       22.945383]]
```

**Comment by thomas-germer** [comment] 2019-10-15 14:07
Thanks for pointing this issue out.  The problem is that Mueller matrices that are on the edge of their space of validity would sometimes be treated as invalid, due to numerical errors. The solution to this was to add a small amount of a totally depolarizing Mueller matrix before testing. This should be fixed in the latest commit.

**Closed as completed by thomas-germer** 2019-10-15 14:07 UTC
